# src/AppBundle/Resources/config/routing.yml

home:
    path: /
    defaults: { _controller: AppBundle:Home:index }
    methods: [GET]

about:
    path: /about
    defaults: { _controller: AppBundle:About:index }
    methods: [GET]

blog:
    path: /blog
    defaults: { _controller: AppBundle:Blog:index }
    requirements:
        _methods: GET

blog_show:
    path: /blog/{id}
    defaults: { _controller: AppBundle:Blog:show }
    requirements:
        _methods: GET
        id: \d+

contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:index }
    requirements:
        _methods: GET|POST